import { Router } from 'express';
import dockerRouter from './docker.routes.js';
import workspaceRouter from './workspace.routes.js';
import containerRouter from './container.routes.js';
import imageRouter from './image.routes.js';
import networkRouter from './network.routes.js';
import volumeRouter from './volume.routes.js';
import dockerfileRouter from './dockerfile.routes.js';
import composeRouter from './compose.routes.js';
import monitoringRouter from './monitoring.routes.js';
import registryRouter from '../registry/registry.router.js';
import pluginRouter from './plugin.routes.js';
import swarmRouter from './swarm.routes.js';
import resourceRouter from './resource.routes.js';
import stackRouter from './stack.routes.js';
import backupRouter from './backup.routes.js';
import securityRouter from './security.routes.js';
import eventRouter from './event.routes.js';
import policyRouter from './policy.routes.js';
import hostRouter from './host.routes.js';

const router = Router();

router.use(dockerRouter);
router.use(workspaceRouter);
router.use(containerRouter);
router.use(imageRouter);
router.use(networkRouter);
router.use(volumeRouter);
router.use(dockerfileRouter);
router.use(composeRouter);
router.use(monitoringRouter);
router.use(registryRouter);
router.use(pluginRouter);
router.use(swarmRouter);
router.use(resourceRouter);
router.use(stackRouter);
router.use(backupRouter);
router.use(securityRouter);
router.use(eventRouter);
router.use(policyRouter);
router.use(hostRouter);

export default router;
